// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.0
// source: groupbuy.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroupBuyHTTP_GetAllActivities_FullMethodName = "/api.http.GroupBuyHTTP/GetAllActivities"
	GroupBuyHTTP_GetAllDiscounts_FullMethodName  = "/api.http.GroupBuyHTTP/GetAllDiscounts"
	GroupBuyHTTP_GetDiscountByID_FullMethodName  = "/api.http.GroupBuyHTTP/GetDiscountByID"
	GroupBuyHTTP_MarketTrial_FullMethodName      = "/api.http.GroupBuyHTTP/MarketTrial"
)

// GroupBuyHTTPClient is the client API for GroupBuyHTTP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GroupBuyService HTTP API
type GroupBuyHTTPClient interface {
	// GetAllActivities retrieves all group buy activities
	GetAllActivities(ctx context.Context, in *GetAllActivitiesRequest, opts ...grpc.CallOption) (*GetAllActivitiesReply, error)
	// GetAllDiscounts retrieves all group buy discounts
	GetAllDiscounts(ctx context.Context, in *GetAllDiscountsRequest, opts ...grpc.CallOption) (*GetAllDiscountsReply, error)
	// GetDiscountByID retrieves a group buy discount by ID
	GetDiscountByID(ctx context.Context, in *GetDiscountByIDRequest, opts ...grpc.CallOption) (*GetDiscountByIDReply, error)
	// MarketTrial handles market trial requests
	MarketTrial(ctx context.Context, in *MarketTrialRequest, opts ...grpc.CallOption) (*MarketTrialReply, error)
}

type groupBuyHTTPClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupBuyHTTPClient(cc grpc.ClientConnInterface) GroupBuyHTTPClient {
	return &groupBuyHTTPClient{cc}
}

func (c *groupBuyHTTPClient) GetAllActivities(ctx context.Context, in *GetAllActivitiesRequest, opts ...grpc.CallOption) (*GetAllActivitiesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllActivitiesReply)
	err := c.cc.Invoke(ctx, GroupBuyHTTP_GetAllActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupBuyHTTPClient) GetAllDiscounts(ctx context.Context, in *GetAllDiscountsRequest, opts ...grpc.CallOption) (*GetAllDiscountsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllDiscountsReply)
	err := c.cc.Invoke(ctx, GroupBuyHTTP_GetAllDiscounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupBuyHTTPClient) GetDiscountByID(ctx context.Context, in *GetDiscountByIDRequest, opts ...grpc.CallOption) (*GetDiscountByIDReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscountByIDReply)
	err := c.cc.Invoke(ctx, GroupBuyHTTP_GetDiscountByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupBuyHTTPClient) MarketTrial(ctx context.Context, in *MarketTrialRequest, opts ...grpc.CallOption) (*MarketTrialReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketTrialReply)
	err := c.cc.Invoke(ctx, GroupBuyHTTP_MarketTrial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupBuyHTTPServer is the server API for GroupBuyHTTP service.
// All implementations must embed UnimplementedGroupBuyHTTPServer
// for forward compatibility.
//
// GroupBuyService HTTP API
type GroupBuyHTTPServer interface {
	// GetAllActivities retrieves all group buy activities
	GetAllActivities(context.Context, *GetAllActivitiesRequest) (*GetAllActivitiesReply, error)
	// GetAllDiscounts retrieves all group buy discounts
	GetAllDiscounts(context.Context, *GetAllDiscountsRequest) (*GetAllDiscountsReply, error)
	// GetDiscountByID retrieves a group buy discount by ID
	GetDiscountByID(context.Context, *GetDiscountByIDRequest) (*GetDiscountByIDReply, error)
	// MarketTrial handles market trial requests
	MarketTrial(context.Context, *MarketTrialRequest) (*MarketTrialReply, error)
	mustEmbedUnimplementedGroupBuyHTTPServer()
}

// UnimplementedGroupBuyHTTPServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupBuyHTTPServer struct{}

func (UnimplementedGroupBuyHTTPServer) GetAllActivities(context.Context, *GetAllActivitiesRequest) (*GetAllActivitiesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllActivities not implemented")
}
func (UnimplementedGroupBuyHTTPServer) GetAllDiscounts(context.Context, *GetAllDiscountsRequest) (*GetAllDiscountsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllDiscounts not implemented")
}
func (UnimplementedGroupBuyHTTPServer) GetDiscountByID(context.Context, *GetDiscountByIDRequest) (*GetDiscountByIDReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiscountByID not implemented")
}
func (UnimplementedGroupBuyHTTPServer) MarketTrial(context.Context, *MarketTrialRequest) (*MarketTrialReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MarketTrial not implemented")
}
func (UnimplementedGroupBuyHTTPServer) mustEmbedUnimplementedGroupBuyHTTPServer() {}
func (UnimplementedGroupBuyHTTPServer) testEmbeddedByValue()                      {}

// UnsafeGroupBuyHTTPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupBuyHTTPServer will
// result in compilation errors.
type UnsafeGroupBuyHTTPServer interface {
	mustEmbedUnimplementedGroupBuyHTTPServer()
}

func RegisterGroupBuyHTTPServer(s grpc.ServiceRegistrar, srv GroupBuyHTTPServer) {
	// If the following call panics, it indicates UnimplementedGroupBuyHTTPServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroupBuyHTTP_ServiceDesc, srv)
}

func _GroupBuyHTTP_GetAllActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupBuyHTTPServer).GetAllActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupBuyHTTP_GetAllActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupBuyHTTPServer).GetAllActivities(ctx, req.(*GetAllActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupBuyHTTP_GetAllDiscounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllDiscountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupBuyHTTPServer).GetAllDiscounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupBuyHTTP_GetAllDiscounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupBuyHTTPServer).GetAllDiscounts(ctx, req.(*GetAllDiscountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupBuyHTTP_GetDiscountByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupBuyHTTPServer).GetDiscountByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupBuyHTTP_GetDiscountByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupBuyHTTPServer).GetDiscountByID(ctx, req.(*GetDiscountByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupBuyHTTP_MarketTrial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketTrialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupBuyHTTPServer).MarketTrial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupBuyHTTP_MarketTrial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupBuyHTTPServer).MarketTrial(ctx, req.(*MarketTrialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupBuyHTTP_ServiceDesc is the grpc.ServiceDesc for GroupBuyHTTP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupBuyHTTP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.http.GroupBuyHTTP",
	HandlerType: (*GroupBuyHTTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllActivities",
			Handler:    _GroupBuyHTTP_GetAllActivities_Handler,
		},
		{
			MethodName: "GetAllDiscounts",
			Handler:    _GroupBuyHTTP_GetAllDiscounts_Handler,
		},
		{
			MethodName: "GetDiscountByID",
			Handler:    _GroupBuyHTTP_GetDiscountByID_Handler,
		},
		{
			MethodName: "MarketTrial",
			Handler:    _GroupBuyHTTP_MarketTrial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "groupbuy.proto",
}
