package main

import (
	"fmt"
	"group-buy-market-go/internal/domain"
	"group-buy-market-go/internal/infrastructure"
	"group-buy-market-go/internal/infrastructure/dao"
	httpInterface "group-buy-market-go/internal/interfaces/http"
	"log"
	"net/http"

	"gorm.io/gorm"
)

func main() {
	// Load configuration
	cfg, err := infrastructure.LoadConfig("configs/config.yaml")
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	// Initialize database
	db, err := cfg.InitDB()
	if err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}
	defer func() {
		sqlDB, _ := db.DB()
		sqlDB.Close()
	}()

	// Initialize server with Wire
	server, err := initializeServer(db)
	if err != nil {
		log.Fatalf("Failed to initialize server: %v", err)
	}

	// Register routes
	server.RegisterRoutes()

	log.Printf("Server starting on %s:%d", cfg.Server.Host, cfg.Server.Port)
	// Start server
	addr := fmt.Sprintf("%s:%d", cfg.Server.Host, cfg.Server.Port)
	err = http.ListenAndServe(addr, server)
	if err != nil {
		log.Fatal(err)
	}
}

// Wire initialization function (will be generated by Wire)
func initializeServer(db *gorm.DB) (*httpInterface.Server, error) {
	mySQLGroupBuyActivityDAO := dao.NewMySQLGroupBuyActivityDAO(db)
	mySQLGroupBuyDiscountDAO := dao.NewMySQLGroupBuyDiscountDAO(db)
	groupBuyService := domain.NewGroupBuyService(mySQLGroupBuyActivityDAO, mySQLGroupBuyDiscountDAO)
	server := httpInterface.NewServer(mySQLGroupBuyActivityDAO, groupBuyService)
	return server, nil
}
