// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"group-buy-market-go/internal/conf"
	"group-buy-market-go/internal/domain/activity/service/discount"
	"group-buy-market-go/internal/domain/activity/service/trial/node"
	"group-buy-market-go/internal/domain/trade/biz"
	"group-buy-market-go/internal/domain/trade/biz/filter"
	"group-buy-market-go/internal/infrastructure/adapter/repository"
	"group-buy-market-go/internal/infrastructure/cache"
	"group-buy-market-go/internal/infrastructure/dao"
	"group-buy-market-go/internal/infrastructure/dcc"
	"group-buy-market-go/internal/server"
	"group-buy-market-go/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := dao.NewDB(data, logger)
	groupBuyActivityDAO := dao.NewMySQLGroupBuyActivityDAO(db)
	groupBuyDiscountDAO := dao.NewMySQLGroupBuyDiscountDAO(db)
	skuDAO := dao.NewMySQLSkuDAO(db)
	scSkuActivityDAO := dao.NewMySQLSCSkuActivityDAO(db)
	client, cleanup, err := cache.NewRedisClient(data, logger)
	if err != nil {
		return nil, nil, err
	}
	dccDCC := dcc.NewDCC(client)
	activityRepository := repository.NewActivityRepository(groupBuyActivityDAO, groupBuyDiscountDAO, skuDAO, scSkuActivityDAO, client, dccDCC)
	endNode := node.NewEndNode(logger)
	tagNode := node.NewTagNode(activityRepository, endNode, logger)
	errorNode := node.NewErrorNode(logger)
	zjCalculateService := discount.NewZJCalculateService(logger, activityRepository)
	zkCalculateService := discount.NewZKCalculateService(logger, activityRepository)
	mjCalculateService := discount.NewMJCalculateService(logger, activityRepository)
	nCalculateService := discount.NewNCalculateService(logger, activityRepository)
	marketNode := node.NewMarketNode(tagNode, errorNode, activityRepository, zjCalculateService, zkCalculateService, mjCalculateService, nCalculateService, logger)
	switchNode := node.NewSwitchNode(activityRepository, marketNode, logger)
	rootNode := node.NewRootNode(switchNode, logger)
	activityService := service.NewActivityService(rootNode)
	crowdTagsDAO := dao.NewMySQLCrowdTagsDAO(db)
	crowdTagsDetailDAO := dao.NewMySQLCrowdTagsDetailDAO(db)
	crowdTagsJobDAO := dao.NewMySQLCrowdTagsJobDAO(db)
	tagRepository := repository.NewTagRepository(logger, crowdTagsDAO, crowdTagsDetailDAO, crowdTagsJobDAO, client)
	tagService := service.NewTagService(logger, tagRepository)
	dccService := service.NewDccService(logger, dccDCC)
	groupBuyOrderDAO := dao.NewMySQLGroupBuyOrderDAO(db)
	groupBuyOrderListDAO := dao.NewMySQLGroupBuyOrderListDAO(db)
	tradeRepository := repository.NewTradeRepository(groupBuyOrderDAO, groupBuyOrderListDAO, groupBuyActivityDAO)
	activityUsabilityRuleFilter := filter.NewActivityUsabilityRuleFilter(tradeRepository)
	userTakeLimitRuleFilter := filter.NewUserTakeLimitRuleFilter(tradeRepository)
	tradeRuleFilterFactory := filter.NewTradeRuleFilterFactory(activityUsabilityRuleFilter, userTakeLimitRuleFilter)
	tradeOrder := biz.NewTradeOrder(tradeRepository, tradeRuleFilterFactory, logger)
	tradeService := service.NewTradeService(logger, tradeOrder, rootNode)
	httpServer := server.NewHTTPServer(confServer, activityService, tagService, dccService, tradeService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
