// Code generated by Wire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/google/wire"
	"group-buy-market-go/internal/domain/trade"
	"group-buy-market-go/internal/domain/trade/biz"
	"group-buy-market-go/internal/service"

	"group-buy-market-go/internal/conf"
	"group-buy-market-go/internal/domain/activity/service/discount"
	"group-buy-market-go/internal/domain/activity/service/trial/node"
	"group-buy-market-go/internal/infrastructure/adapter/repository"
	"group-buy-market-go/internal/infrastructure/cache"
	"group-buy-market-go/internal/infrastructure/dao"
	"group-buy-market-go/internal/infrastructure/dcc"
	"group-buy-market-go/internal/server"
)

// wireApp init kratos application.
func wireApp(*conf.Server, *conf.Data, log.Logger) (*kratos.App, func(), error) {
	panic(wire.Build(
		server.ProviderSet,
		dao.ProviderSet,
		cache.ProviderSet,
		dcc.ProviderSet,
		repository.NewActivityRepository,
		repository.NewTagRepository,
		repository.NewTradeRepository,
		trade.ProviderSet,
		biz.NewTradeOrder,
		node.NewRootNode,
		service.NewTagService,
		service.NewDccService,
		service.NewActivityService,
		service.NewTradeService,
		discount.NewZJCalculateService,
		discount.NewZKCalculateService,
		discount.NewMJCalculateService,
		discount.NewNCalculateService,
		node.NewEndNode,
		node.NewErrorNode,
		node.NewMarketNode,
		node.NewSwitchNode,
		node.NewTagNode,
		newApp,
	))
}
