// Code generated by Wire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/google/wire"
	"group-buy-market-go/internal/domain/activity/service/trial"
	"group-buy-market-go/internal/domain/trade"
	"group-buy-market-go/internal/infrastructure"
	"group-buy-market-go/internal/service"

	"group-buy-market-go/internal/conf"
	"group-buy-market-go/internal/domain/activity/biz/discount"
	"group-buy-market-go/internal/server"
)

// wireApp init kratos application.
func wireApp(*conf.Server, *conf.Data, log.Logger) (*kratos.App, func(), error) {
	panic(wire.Build(
		server.ProviderSet,
		infrastructure.ProviderSet,
		trade.ProviderSet,
		service.ProviderSet,
		discount.ProviderSet,
		trial.ProviderSet,
		newApp,
	))
}
