// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"group-buy-market-go/internal/conf"
	"group-buy-market-go/internal/domain/activity/service"
	"group-buy-market-go/internal/domain/activity/service/discount"
	"group-buy-market-go/internal/domain/activity/service/trial/node"
	service2 "group-buy-market-go/internal/domain/tag/service"
	"group-buy-market-go/internal/infrastructure/adapter/repository"
	"group-buy-market-go/internal/infrastructure/cache"
	"group-buy-market-go/internal/infrastructure/dao"
	"group-buy-market-go/internal/infrastructure/dcc"
	"group-buy-market-go/internal/server"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := dao.NewDB(data, logger)
	groupBuyActivityDAO := dao.NewMySQLGroupBuyActivityDAO(db)
	groupBuyDiscountDAO := dao.NewMySQLGroupBuyDiscountDAO(db)
	skuDAO := dao.NewMySQLSkuDAO(db)
	scSkuActivityDAO := dao.NewMySQLSCSkuActivityDAO(db)
	client, cleanup, err := cache.NewRedisClient(data, logger)
	if err != nil {
		return nil, nil, err
	}
	dccDCC := dcc.NewDCC(client)
	activityRepository := repository.NewActivityRepository(groupBuyActivityDAO, groupBuyDiscountDAO, skuDAO, scSkuActivityDAO, client, dccDCC)
	endNode := node.NewEndNode(logger)
	tagNode := node.NewTagNode(activityRepository, endNode, logger)
	errorNode := node.NewErrorNode(logger)
	zjCalculateService := discount.NewZJCalculateService(logger)
	zkCalculateService := discount.NewZKCalculateService(logger)
	mjCalculateService := discount.NewMJCalculateService(logger)
	nCalculateService := discount.NewNCalculateService(logger)
	marketNode := node.NewMarketNode(tagNode, errorNode, activityRepository, zjCalculateService, zkCalculateService, mjCalculateService, nCalculateService, logger)
	switchNode := node.NewSwitchNode(activityRepository, marketNode, logger)
	rootNode := node.NewRootNode(switchNode, logger)
	iIndexGroupBuyMarketService := service.NewIIndexGroupBuyMarketService(rootNode)
	crowdTagsDAO := dao.NewMySQLCrowdTagsDAO(db)
	crowdTagsDetailDAO := dao.NewMySQLCrowdTagsDetailDAO(db)
	crowdTagsJobDAO := dao.NewMySQLCrowdTagsJobDAO(db)
	tagRepository := repository.NewTagRepository(logger, crowdTagsDAO, crowdTagsDetailDAO, crowdTagsJobDAO, client)
	tagService := service2.NewTagService(logger, tagRepository)
	httpServer := server.NewHTTPServer(confServer, iIndexGroupBuyMarketService, tagService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
