// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"group-buy-market-go/internal/conf"
	"group-buy-market-go/internal/domain/activity/service/discount"
	"group-buy-market-go/internal/domain/activity/service/trial/node"
	"group-buy-market-go/internal/domain/trade/biz/lock"
	"group-buy-market-go/internal/domain/trade/biz/lock/filter"
	"group-buy-market-go/internal/infrastructure/adapter/repository"
	"group-buy-market-go/internal/infrastructure/dao"
	"group-buy-market-go/internal/infrastructure/data"
	"group-buy-market-go/internal/infrastructure/dcc"
	"group-buy-market-go/internal/server"
	"group-buy-market-go/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData := data.NewData(db)
	groupBuyActivityDAO := dao.NewMySQLGroupBuyActivityDAO(dataData)
	groupBuyDiscountDAO := dao.NewMySQLGroupBuyDiscountDAO(dataData)
	skuDAO := dao.NewMySQLSkuDAO(dataData)
	scSkuActivityDAO := dao.NewMySQLSCSkuActivityDAO(dataData)
	client, cleanup, err := data.NewRedisClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dccDCC := dcc.NewDCC(client)
	activityRepository := repository.NewActivityRepository(groupBuyActivityDAO, groupBuyDiscountDAO, skuDAO, scSkuActivityDAO, client, dccDCC)
	endNode := node.NewEndNode(logger)
	tagNode := node.NewTagNode(activityRepository, endNode, logger)
	errorNode := node.NewErrorNode(logger)
	zjCalculateService := discount.NewZJCalculateService(logger, activityRepository)
	zkCalculateService := discount.NewZKCalculateService(logger, activityRepository)
	mjCalculateService := discount.NewMJCalculateService(logger, activityRepository)
	nCalculateService := discount.NewNCalculateService(logger, activityRepository)
	marketNode := node.NewMarketNode(tagNode, errorNode, activityRepository, zjCalculateService, zkCalculateService, mjCalculateService, nCalculateService, logger)
	switchNode := node.NewSwitchNode(activityRepository, marketNode, logger)
	rootNode := node.NewRootNode(switchNode, logger)
	activityService := service.NewActivityService(rootNode)
	crowdTagsDAO := dao.NewMySQLCrowdTagsDAO(dataData)
	crowdTagsDetailDAO := dao.NewMySQLCrowdTagsDetailDAO(dataData)
	crowdTagsJobDAO := dao.NewMySQLCrowdTagsJobDAO(dataData)
	tagRepository := repository.NewTagRepository(logger, crowdTagsDAO, crowdTagsDetailDAO, crowdTagsJobDAO, client)
	tagService := service.NewTagService(logger, tagRepository)
	dccService := service.NewDccService(logger, dccDCC)
	groupBuyOrderDAO := dao.NewMySQLGroupBuyOrderDAO(dataData)
	groupBuyOrderListDAO := dao.NewMySQLGroupBuyOrderListDAO(dataData)
	notifyTaskDAO := dao.NewMySQLNotifyTaskDAO(dataData)
	tradeRepository := repository.NewTradeRepository(dataData, groupBuyOrderDAO, groupBuyOrderListDAO, groupBuyActivityDAO, notifyTaskDAO)
	activityUsabilityRuleFilter := filter.NewActivityUsabilityRuleFilter(logger, tradeRepository)
	userTakeLimitRuleFilter := filter.NewUserTakeLimitRuleFilter(logger, tradeRepository)
	tradeLockRuleFilterFactory := filter.NewTradeLockRuleFilterFactory(activityUsabilityRuleFilter, userTakeLimitRuleFilter)
	tradeLockOrder := lock.NewTradeLockOrder(tradeRepository, tradeLockRuleFilterFactory, logger)
	tradeService := service.NewTradeService(logger, tradeLockOrder, rootNode)
	httpServer := server.NewHTTPServer(confServer, activityService, tagService, dccService, tradeService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
