// Code generated by Wire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/google/wire"

	"group-buy-market-go/internal/conf"
	activity_service "group-buy-market-go/internal/domain/activity/service"
	"group-buy-market-go/internal/domain/activity/service/discount"
	"group-buy-market-go/internal/domain/activity/service/trial/node"
	tag_service "group-buy-market-go/internal/domain/tag/service"
	"group-buy-market-go/internal/infrastructure/adapter/repository"
	"group-buy-market-go/internal/infrastructure/cache"
	"group-buy-market-go/internal/infrastructure/dao"
	"group-buy-market-go/internal/server"
)

// wireApp init kratos application.
func wireApp(*conf.Server, *conf.Data, log.Logger) (*kratos.App, func(), error) {
	panic(wire.Build(
		server.ProviderSet,
		dao.ProviderSet,
		cache.ProviderSet,
		repository.NewActivityRepository,
		repository.NewTagRepository,
		tag_service.NewTagService,
		discount.NewZJCalculateService,
		discount.NewZKCalculateService,
		discount.NewMJCalculateService,
		discount.NewNCalculateService,
		node.NewEndNode,
		node.NewErrorNode,
		node.NewMarketNode,
		node.NewSwitchNode,
		node.NewRootNode,
		activity_service.NewIIndexGroupBuyMarketService,
		newApp,
	))
}
