// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.27.0
// source: api/v1/activity.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationActivityHTTPMarketTrial = "/api.v1.ActivityHTTP/MarketTrial"

type ActivityHTTPHTTPServer interface {
	// MarketTrial MarketTrial handles market trial requests
	MarketTrial(context.Context, *MarketTrialRequest) (*MarketTrialReply, error)
}

func RegisterActivityHTTPHTTPServer(s *http.Server, srv ActivityHTTPHTTPServer) {
	r := s.Route("/")
	r.POST("/market/trial", _ActivityHTTP_MarketTrial0_HTTP_Handler(srv))
}

func _ActivityHTTP_MarketTrial0_HTTP_Handler(srv ActivityHTTPHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarketTrialRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationActivityHTTPMarketTrial)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarketTrial(ctx, req.(*MarketTrialRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MarketTrialReply)
		return ctx.Result(200, reply)
	}
}

type ActivityHTTPHTTPClient interface {
	// MarketTrial MarketTrial handles market trial requests
	MarketTrial(ctx context.Context, req *MarketTrialRequest, opts ...http.CallOption) (rsp *MarketTrialReply, err error)
}

type ActivityHTTPHTTPClientImpl struct {
	cc *http.Client
}

func NewActivityHTTPHTTPClient(client *http.Client) ActivityHTTPHTTPClient {
	return &ActivityHTTPHTTPClientImpl{client}
}

// MarketTrial MarketTrial handles market trial requests
func (c *ActivityHTTPHTTPClientImpl) MarketTrial(ctx context.Context, in *MarketTrialRequest, opts ...http.CallOption) (*MarketTrialReply, error) {
	var out MarketTrialReply
	pattern := "/market/trial"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationActivityHTTPMarketTrial))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
