// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: api/v1/activity.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketTrialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GoodsId       string                 `protobuf:"bytes,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketTrialRequest) Reset() {
	*x = MarketTrialRequest{}
	mi := &file_api_v1_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketTrialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketTrialRequest) ProtoMessage() {}

func (x *MarketTrialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketTrialRequest.ProtoReflect.Descriptor instead.
func (*MarketTrialRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_activity_proto_rawDescGZIP(), []int{0}
}

func (x *MarketTrialRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarketTrialRequest) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *MarketTrialRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MarketTrialRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type MarketTrialReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrialResult   *TrialBalanceInfo      `protobuf:"bytes,1,opt,name=trial_result,json=trialResult,proto3" json:"trial_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketTrialReply) Reset() {
	*x = MarketTrialReply{}
	mi := &file_api_v1_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketTrialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketTrialReply) ProtoMessage() {}

func (x *MarketTrialReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketTrialReply.ProtoReflect.Descriptor instead.
func (*MarketTrialReply) Descriptor() ([]byte, []int) {
	return file_api_v1_activity_proto_rawDescGZIP(), []int{1}
}

func (x *MarketTrialReply) GetTrialResult() *TrialBalanceInfo {
	if x != nil {
		return x.TrialResult
	}
	return nil
}

type TrialBalanceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GoodsId        string                 `protobuf:"bytes,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsName      string                 `protobuf:"bytes,2,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	OriginalPrice  float64                `protobuf:"fixed64,3,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	DeductionPrice float64                `protobuf:"fixed64,4,opt,name=deduction_price,json=deductionPrice,proto3" json:"deduction_price,omitempty"`
	TargetCount    int32                  `protobuf:"varint,5,opt,name=target_count,json=targetCount,proto3" json:"target_count,omitempty"`
	StartTime      int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsVisible      bool                   `protobuf:"varint,8,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	IsEnable       bool                   `protobuf:"varint,9,opt,name=is_enable,json=isEnable,proto3" json:"is_enable,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrialBalanceInfo) Reset() {
	*x = TrialBalanceInfo{}
	mi := &file_api_v1_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrialBalanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrialBalanceInfo) ProtoMessage() {}

func (x *TrialBalanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrialBalanceInfo.ProtoReflect.Descriptor instead.
func (*TrialBalanceInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_activity_proto_rawDescGZIP(), []int{2}
}

func (x *TrialBalanceInfo) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *TrialBalanceInfo) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *TrialBalanceInfo) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *TrialBalanceInfo) GetDeductionPrice() float64 {
	if x != nil {
		return x.DeductionPrice
	}
	return 0
}

func (x *TrialBalanceInfo) GetTargetCount() int32 {
	if x != nil {
		return x.TargetCount
	}
	return 0
}

func (x *TrialBalanceInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TrialBalanceInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TrialBalanceInfo) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *TrialBalanceInfo) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

var File_api_v1_activity_proto protoreflect.FileDescriptor

const file_api_v1_activity_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/activity.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\"z\n" +
	"\x12MarketTrialRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgoods_id\x18\x02 \x01(\tR\agoodsId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\"O\n" +
	"\x10MarketTrialReply\x12;\n" +
	"\ftrial_result\x18\x01 \x01(\v2\x18.api.v1.TrialBalanceInfoR\vtrialResult\"\xb5\x02\n" +
	"\x10TrialBalanceInfo\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\tR\agoodsId\x12\x1d\n" +
	"\n" +
	"goods_name\x18\x02 \x01(\tR\tgoodsName\x12%\n" +
	"\x0eoriginal_price\x18\x03 \x01(\x01R\roriginalPrice\x12'\n" +
	"\x0fdeduction_price\x18\x04 \x01(\x01R\x0edeductionPrice\x12!\n" +
	"\ftarget_count\x18\x05 \x01(\x05R\vtargetCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x1d\n" +
	"\n" +
	"is_visible\x18\b \x01(\bR\tisVisible\x12\x1b\n" +
	"\tis_enable\x18\t \x01(\bR\bisEnable2m\n" +
	"\fActivityHTTP\x12]\n" +
	"\vMarketTrial\x12\x1a.api.v1.MarketTrialRequest\x1a\x18.api.v1.MarketTrialReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/market/trialB\x1fZ\x1dgroup-buy-market-go/api/v1;v1b\x06proto3"

var (
	file_api_v1_activity_proto_rawDescOnce sync.Once
	file_api_v1_activity_proto_rawDescData []byte
)

func file_api_v1_activity_proto_rawDescGZIP() []byte {
	file_api_v1_activity_proto_rawDescOnce.Do(func() {
		file_api_v1_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_activity_proto_rawDesc), len(file_api_v1_activity_proto_rawDesc)))
	})
	return file_api_v1_activity_proto_rawDescData
}

var file_api_v1_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_activity_proto_goTypes = []any{
	(*MarketTrialRequest)(nil), // 0: api.v1.MarketTrialRequest
	(*MarketTrialReply)(nil),   // 1: api.v1.MarketTrialReply
	(*TrialBalanceInfo)(nil),   // 2: api.v1.TrialBalanceInfo
}
var file_api_v1_activity_proto_depIdxs = []int32{
	2, // 0: api.v1.MarketTrialReply.trial_result:type_name -> api.v1.TrialBalanceInfo
	0, // 1: api.v1.ActivityHTTP.MarketTrial:input_type -> api.v1.MarketTrialRequest
	1, // 2: api.v1.ActivityHTTP.MarketTrial:output_type -> api.v1.MarketTrialReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_activity_proto_init() }
func file_api_v1_activity_proto_init() {
	if File_api_v1_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_activity_proto_rawDesc), len(file_api_v1_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_activity_proto_goTypes,
		DependencyIndexes: file_api_v1_activity_proto_depIdxs,
		MessageInfos:      file_api_v1_activity_proto_msgTypes,
	}.Build()
	File_api_v1_activity_proto = out.File
	file_api_v1_activity_proto_goTypes = nil
	file_api_v1_activity_proto_depIdxs = nil
}
