// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.0
// source: api/v1/activity.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivityHTTP_MarketTrial_FullMethodName = "/api.v1.ActivityHTTP/MarketTrial"
)

// ActivityHTTPClient is the client API for ActivityHTTP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GroupBuyService HTTP API
type ActivityHTTPClient interface {
	// MarketTrial handles market trial requests
	MarketTrial(ctx context.Context, in *MarketTrialRequest, opts ...grpc.CallOption) (*MarketTrialReply, error)
}

type activityHTTPClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityHTTPClient(cc grpc.ClientConnInterface) ActivityHTTPClient {
	return &activityHTTPClient{cc}
}

func (c *activityHTTPClient) MarketTrial(ctx context.Context, in *MarketTrialRequest, opts ...grpc.CallOption) (*MarketTrialReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketTrialReply)
	err := c.cc.Invoke(ctx, ActivityHTTP_MarketTrial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityHTTPServer is the server API for ActivityHTTP service.
// All implementations must embed UnimplementedActivityHTTPServer
// for forward compatibility.
//
// GroupBuyService HTTP API
type ActivityHTTPServer interface {
	// MarketTrial handles market trial requests
	MarketTrial(context.Context, *MarketTrialRequest) (*MarketTrialReply, error)
	mustEmbedUnimplementedActivityHTTPServer()
}

// UnimplementedActivityHTTPServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityHTTPServer struct{}

func (UnimplementedActivityHTTPServer) MarketTrial(context.Context, *MarketTrialRequest) (*MarketTrialReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MarketTrial not implemented")
}
func (UnimplementedActivityHTTPServer) mustEmbedUnimplementedActivityHTTPServer() {}
func (UnimplementedActivityHTTPServer) testEmbeddedByValue()                      {}

// UnsafeActivityHTTPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityHTTPServer will
// result in compilation errors.
type UnsafeActivityHTTPServer interface {
	mustEmbedUnimplementedActivityHTTPServer()
}

func RegisterActivityHTTPServer(s grpc.ServiceRegistrar, srv ActivityHTTPServer) {
	// If the following call panics, it indicates UnimplementedActivityHTTPServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivityHTTP_ServiceDesc, srv)
}

func _ActivityHTTP_MarketTrial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketTrialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityHTTPServer).MarketTrial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityHTTP_MarketTrial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityHTTPServer).MarketTrial(ctx, req.(*MarketTrialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivityHTTP_ServiceDesc is the grpc.ServiceDesc for ActivityHTTP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityHTTP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.ActivityHTTP",
	HandlerType: (*ActivityHTTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MarketTrial",
			Handler:    _ActivityHTTP_MarketTrial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/activity.proto",
}
