// Code generated by protoc-gen-go-http. DO NOT EDIT.

package v1

import (
	context "context"
	middleware "github.com/go-kratos/kratos/v2/middleware"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
// context./http./middleware.
const _ = http1.SupportPackageIsVersion1

type ActivityHTTPHTTPServer interface {
	MarketTrial(context.Context, *MarketTrialRequest) (*MarketTrialReply, error)
}

func RegisterActivityHTTPHTTPServer(s http1.ServiceRegistrar, srv ActivityHTTPHTTPServer) {
	s.RegisterService(&_HTTP_ActivityHTTP_serviceDesc, srv)
}

func _HTTP_ActivityHTTP_MarketTrial_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in MarketTrialRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityHTTPServer).MarketTrial(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _HTTP_ActivityHTTP_serviceDesc = http1.ServiceDesc{
	ServiceName: "api.http.ActivityHTTP",
	Methods: []http1.MethodDesc{

		{
			Path:    "/market/trial",
			Method:  "GET",
			Handler: _HTTP_ActivityHTTP_MarketTrial_0,
		},
	},
	Metadata: "api/v1/activity.proto",
}
