// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: api/v1/dcc.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_api_v1_dcc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dcc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_dcc_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigReply) Reset() {
	*x = UpdateConfigReply{}
	mi := &file_api_v1_dcc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigReply) ProtoMessage() {}

func (x *UpdateConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dcc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigReply.ProtoReflect.Descriptor instead.
func (*UpdateConfigReply) Descriptor() ([]byte, []int) {
	return file_api_v1_dcc_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateConfigReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_v1_dcc_proto protoreflect.FileDescriptor

const file_api_v1_dcc_proto_rawDesc = "" +
	"\n" +
	"\x10api/v1/dcc.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\"=\n" +
	"\x13UpdateConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"-\n" +
	"\x11UpdateConfigReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2o\n" +
	"\aDccHTTP\x12d\n" +
	"\fUpdateConfig\x12\x1b.api.v1.UpdateConfigRequest\x1a\x19.api.v1.UpdateConfigReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/dcc/updateConfigB\x1fZ\x1dgroup-buy-market-go/api/v1;v1b\x06proto3"

var (
	file_api_v1_dcc_proto_rawDescOnce sync.Once
	file_api_v1_dcc_proto_rawDescData []byte
)

func file_api_v1_dcc_proto_rawDescGZIP() []byte {
	file_api_v1_dcc_proto_rawDescOnce.Do(func() {
		file_api_v1_dcc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_dcc_proto_rawDesc), len(file_api_v1_dcc_proto_rawDesc)))
	})
	return file_api_v1_dcc_proto_rawDescData
}

var file_api_v1_dcc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_dcc_proto_goTypes = []any{
	(*UpdateConfigRequest)(nil), // 0: api.v1.UpdateConfigRequest
	(*UpdateConfigReply)(nil),   // 1: api.v1.UpdateConfigReply
}
var file_api_v1_dcc_proto_depIdxs = []int32{
	0, // 0: api.v1.DccHTTP.UpdateConfig:input_type -> api.v1.UpdateConfigRequest
	1, // 1: api.v1.DccHTTP.UpdateConfig:output_type -> api.v1.UpdateConfigReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_dcc_proto_init() }
func file_api_v1_dcc_proto_init() {
	if File_api_v1_dcc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_dcc_proto_rawDesc), len(file_api_v1_dcc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_dcc_proto_goTypes,
		DependencyIndexes: file_api_v1_dcc_proto_depIdxs,
		MessageInfos:      file_api_v1_dcc_proto_msgTypes,
	}.Build()
	File_api_v1_dcc_proto = out.File
	file_api_v1_dcc_proto_goTypes = nil
	file_api_v1_dcc_proto_depIdxs = nil
}
