// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.27.0
// source: api/v1/dcc.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDccHTTPUpdateConfig = "/api.v1.DccHTTP/UpdateConfig"

type DccHTTPHTTPServer interface {
	// UpdateConfig UpdateConfig
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigReply, error)
}

func RegisterDccHTTPHTTPServer(s *http.Server, srv DccHTTPHTTPServer) {
	r := s.Route("/")
	r.POST("/dcc/updateConfig", _DccHTTP_UpdateConfig0_HTTP_Handler(srv))
}

func _DccHTTP_UpdateConfig0_HTTP_Handler(srv DccHTTPHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDccHTTPUpdateConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateConfig(ctx, req.(*UpdateConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateConfigReply)
		return ctx.Result(200, reply)
	}
}

type DccHTTPHTTPClient interface {
	// UpdateConfig UpdateConfig
	UpdateConfig(ctx context.Context, req *UpdateConfigRequest, opts ...http.CallOption) (rsp *UpdateConfigReply, err error)
}

type DccHTTPHTTPClientImpl struct {
	cc *http.Client
}

func NewDccHTTPHTTPClient(client *http.Client) DccHTTPHTTPClient {
	return &DccHTTPHTTPClientImpl{client}
}

// UpdateConfig UpdateConfig
func (c *DccHTTPHTTPClientImpl) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...http.CallOption) (*UpdateConfigReply, error) {
	var out UpdateConfigReply
	pattern := "/dcc/updateConfig"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDccHTTPUpdateConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
