// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.0
// source: api/v1/index.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexHTTP_LockMarketPayOrder_FullMethodName = "/api.v1.IndexHTTP/LockMarketPayOrder"
)

// IndexHTTPClient is the client API for IndexHTTP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IndexService HTTP API
type IndexHTTPClient interface {
	// QueryGroupBuyMarketConfig 查询拼团营销配置
	LockMarketPayOrder(ctx context.Context, in *QueryGroupBuyMarketConfigRequest, opts ...grpc.CallOption) (*QueryGroupBuyMarketConfigReply, error)
}

type indexHTTPClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexHTTPClient(cc grpc.ClientConnInterface) IndexHTTPClient {
	return &indexHTTPClient{cc}
}

func (c *indexHTTPClient) LockMarketPayOrder(ctx context.Context, in *QueryGroupBuyMarketConfigRequest, opts ...grpc.CallOption) (*QueryGroupBuyMarketConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGroupBuyMarketConfigReply)
	err := c.cc.Invoke(ctx, IndexHTTP_LockMarketPayOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexHTTPServer is the server API for IndexHTTP service.
// All implementations must embed UnimplementedIndexHTTPServer
// for forward compatibility.
//
// IndexService HTTP API
type IndexHTTPServer interface {
	// QueryGroupBuyMarketConfig 查询拼团营销配置
	LockMarketPayOrder(context.Context, *QueryGroupBuyMarketConfigRequest) (*QueryGroupBuyMarketConfigReply, error)
	mustEmbedUnimplementedIndexHTTPServer()
}

// UnimplementedIndexHTTPServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexHTTPServer struct{}

func (UnimplementedIndexHTTPServer) LockMarketPayOrder(context.Context, *QueryGroupBuyMarketConfigRequest) (*QueryGroupBuyMarketConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LockMarketPayOrder not implemented")
}
func (UnimplementedIndexHTTPServer) mustEmbedUnimplementedIndexHTTPServer() {}
func (UnimplementedIndexHTTPServer) testEmbeddedByValue()                   {}

// UnsafeIndexHTTPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexHTTPServer will
// result in compilation errors.
type UnsafeIndexHTTPServer interface {
	mustEmbedUnimplementedIndexHTTPServer()
}

func RegisterIndexHTTPServer(s grpc.ServiceRegistrar, srv IndexHTTPServer) {
	// If the following call panics, it indicates UnimplementedIndexHTTPServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexHTTP_ServiceDesc, srv)
}

func _IndexHTTP_LockMarketPayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGroupBuyMarketConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexHTTPServer).LockMarketPayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexHTTP_LockMarketPayOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexHTTPServer).LockMarketPayOrder(ctx, req.(*QueryGroupBuyMarketConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexHTTP_ServiceDesc is the grpc.ServiceDesc for IndexHTTP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexHTTP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.IndexHTTP",
	HandlerType: (*IndexHTTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LockMarketPayOrder",
			Handler:    _IndexHTTP_LockMarketPayOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/index.proto",
}
