// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.27.0
// source: api/v1/index.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationIndexHTTPLockMarketPayOrder = "/api.v1.IndexHTTP/LockMarketPayOrder"

type IndexHTTPHTTPServer interface {
	// LockMarketPayOrder QueryGroupBuyMarketConfig 查询拼团营销配置
	LockMarketPayOrder(context.Context, *QueryGroupBuyMarketConfigRequest) (*QueryGroupBuyMarketConfigReply, error)
}

func RegisterIndexHTTPHTTPServer(s *http.Server, srv IndexHTTPHTTPServer) {
	r := s.Route("/")
	r.POST("/index/queryGroupBuyMarketConfig", _IndexHTTP_LockMarketPayOrder0_HTTP_Handler(srv))
}

func _IndexHTTP_LockMarketPayOrder0_HTTP_Handler(srv IndexHTTPHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryGroupBuyMarketConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIndexHTTPLockMarketPayOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LockMarketPayOrder(ctx, req.(*QueryGroupBuyMarketConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryGroupBuyMarketConfigReply)
		return ctx.Result(200, reply)
	}
}

type IndexHTTPHTTPClient interface {
	// LockMarketPayOrder QueryGroupBuyMarketConfig 查询拼团营销配置
	LockMarketPayOrder(ctx context.Context, req *QueryGroupBuyMarketConfigRequest, opts ...http.CallOption) (rsp *QueryGroupBuyMarketConfigReply, err error)
}

type IndexHTTPHTTPClientImpl struct {
	cc *http.Client
}

func NewIndexHTTPHTTPClient(client *http.Client) IndexHTTPHTTPClient {
	return &IndexHTTPHTTPClientImpl{client}
}

// LockMarketPayOrder QueryGroupBuyMarketConfig 查询拼团营销配置
func (c *IndexHTTPHTTPClientImpl) LockMarketPayOrder(ctx context.Context, in *QueryGroupBuyMarketConfigRequest, opts ...http.CallOption) (*QueryGroupBuyMarketConfigReply, error) {
	var out QueryGroupBuyMarketConfigReply
	pattern := "/index/queryGroupBuyMarketConfig"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIndexHTTPLockMarketPayOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
