// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: api/v1/index.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryGroupBuyMarketConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	GoodsId       string                 `protobuf:"bytes,4,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGroupBuyMarketConfigRequest) Reset() {
	*x = QueryGroupBuyMarketConfigRequest{}
	mi := &file_api_v1_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGroupBuyMarketConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGroupBuyMarketConfigRequest) ProtoMessage() {}

func (x *QueryGroupBuyMarketConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGroupBuyMarketConfigRequest.ProtoReflect.Descriptor instead.
func (*QueryGroupBuyMarketConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_index_proto_rawDescGZIP(), []int{0}
}

func (x *QueryGroupBuyMarketConfigRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryGroupBuyMarketConfigRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueryGroupBuyMarketConfigRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *QueryGroupBuyMarketConfigRequest) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

// 商品营销应答对象
type QueryGroupBuyMarketConfigReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品信息
	Goods *Goods `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`
	// 组队信息（1个个人的置顶、2个随机的「获取10个，随机取2个」）
	TeamList []*Team `protobuf:"bytes,2,rep,name=team_list,json=teamList,proto3" json:"team_list,omitempty"`
	// 组队统计
	TeamStatistic *TeamStatistic `protobuf:"bytes,3,opt,name=team_statistic,json=teamStatistic,proto3" json:"team_statistic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGroupBuyMarketConfigReply) Reset() {
	*x = QueryGroupBuyMarketConfigReply{}
	mi := &file_api_v1_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGroupBuyMarketConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGroupBuyMarketConfigReply) ProtoMessage() {}

func (x *QueryGroupBuyMarketConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGroupBuyMarketConfigReply.ProtoReflect.Descriptor instead.
func (*QueryGroupBuyMarketConfigReply) Descriptor() ([]byte, []int) {
	return file_api_v1_index_proto_rawDescGZIP(), []int{1}
}

func (x *QueryGroupBuyMarketConfigReply) GetGoods() *Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

func (x *QueryGroupBuyMarketConfigReply) GetTeamList() []*Team {
	if x != nil {
		return x.TeamList
	}
	return nil
}

func (x *QueryGroupBuyMarketConfigReply) GetTeamStatistic() *TeamStatistic {
	if x != nil {
		return x.TeamStatistic
	}
	return nil
}

// 商品信息
type Goods struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品ID
	GoodsId string `protobuf:"bytes,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	// 原始价格
	OriginalPrice float64 `protobuf:"fixed64,2,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	// 折扣金额
	DeductionPrice float64 `protobuf:"fixed64,3,opt,name=deduction_price,json=deductionPrice,proto3" json:"deduction_price,omitempty"`
	// 支付价格
	PayPrice      float64 `protobuf:"fixed64,4,opt,name=pay_price,json=payPrice,proto3" json:"pay_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goods) Reset() {
	*x = Goods{}
	mi := &file_api_v1_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_api_v1_index_proto_rawDescGZIP(), []int{2}
}

func (x *Goods) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *Goods) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *Goods) GetDeductionPrice() float64 {
	if x != nil {
		return x.DeductionPrice
	}
	return 0
}

func (x *Goods) GetPayPrice() float64 {
	if x != nil {
		return x.PayPrice
	}
	return 0
}

// 组队信息
type Team struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 拼单组队ID
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// 活动ID
	ActivityId int64 `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	// 目标数量
	TargetCount int32 `protobuf:"varint,4,opt,name=target_count,json=targetCount,proto3" json:"target_count,omitempty"`
	// 完成数量
	CompleteCount int32 `protobuf:"varint,5,opt,name=complete_count,json=completeCount,proto3" json:"complete_count,omitempty"`
	// 锁单数量
	LockCount int32 `protobuf:"varint,6,opt,name=lock_count,json=lockCount,proto3" json:"lock_count,omitempty"`
	// 拼团开始时间 - 参与拼团时间
	ValidStartTime int64 `protobuf:"varint,7,opt,name=valid_start_time,json=validStartTime,proto3" json:"valid_start_time,omitempty"`
	// 拼团结束时间 - 拼团有效时长
	ValidEndTime int64 `protobuf:"varint,8,opt,name=valid_end_time,json=validEndTime,proto3" json:"valid_end_time,omitempty"`
	// 倒计时(字符串) validEndTime - validStartTime
	ValidTimeCountdown string `protobuf:"bytes,9,opt,name=valid_time_countdown,json=validTimeCountdown,proto3" json:"valid_time_countdown,omitempty"`
	// 外部交易单号-确保外部调用唯一幂等
	OutTradeNo    string `protobuf:"bytes,10,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_api_v1_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_api_v1_index_proto_rawDescGZIP(), []int{3}
}

func (x *Team) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Team) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Team) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *Team) GetTargetCount() int32 {
	if x != nil {
		return x.TargetCount
	}
	return 0
}

func (x *Team) GetCompleteCount() int32 {
	if x != nil {
		return x.CompleteCount
	}
	return 0
}

func (x *Team) GetLockCount() int32 {
	if x != nil {
		return x.LockCount
	}
	return 0
}

func (x *Team) GetValidStartTime() int64 {
	if x != nil {
		return x.ValidStartTime
	}
	return 0
}

func (x *Team) GetValidEndTime() int64 {
	if x != nil {
		return x.ValidEndTime
	}
	return 0
}

func (x *Team) GetValidTimeCountdown() string {
	if x != nil {
		return x.ValidTimeCountdown
	}
	return ""
}

func (x *Team) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

// 组队统计
type TeamStatistic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 开团队伍数量
	AllTeamCount int32 `protobuf:"varint,1,opt,name=all_team_count,json=allTeamCount,proto3" json:"all_team_count,omitempty"`
	// 成团队伍数量
	AllTeamCompleteCount int32 `protobuf:"varint,2,opt,name=all_team_complete_count,json=allTeamCompleteCount,proto3" json:"all_team_complete_count,omitempty"`
	// 参团人数总量 - 一个商品的总参团人数
	AllTeamUserCount int32 `protobuf:"varint,3,opt,name=all_team_user_count,json=allTeamUserCount,proto3" json:"all_team_user_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TeamStatistic) Reset() {
	*x = TeamStatistic{}
	mi := &file_api_v1_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStatistic) ProtoMessage() {}

func (x *TeamStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStatistic.ProtoReflect.Descriptor instead.
func (*TeamStatistic) Descriptor() ([]byte, []int) {
	return file_api_v1_index_proto_rawDescGZIP(), []int{4}
}

func (x *TeamStatistic) GetAllTeamCount() int32 {
	if x != nil {
		return x.AllTeamCount
	}
	return 0
}

func (x *TeamStatistic) GetAllTeamCompleteCount() int32 {
	if x != nil {
		return x.AllTeamCompleteCount
	}
	return 0
}

func (x *TeamStatistic) GetAllTeamUserCount() int32 {
	if x != nil {
		return x.AllTeamUserCount
	}
	return 0
}

var File_api_v1_index_proto protoreflect.FileDescriptor

const file_api_v1_index_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/index.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\"\x88\x01\n" +
	" QueryGroupBuyMarketConfigRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x19\n" +
	"\bgoods_id\x18\x04 \x01(\tR\agoodsId\"\xae\x01\n" +
	"\x1eQueryGroupBuyMarketConfigReply\x12#\n" +
	"\x05goods\x18\x01 \x01(\v2\r.api.v1.GoodsR\x05goods\x12)\n" +
	"\tteam_list\x18\x02 \x03(\v2\f.api.v1.TeamR\bteamList\x12<\n" +
	"\x0eteam_statistic\x18\x03 \x01(\v2\x15.api.v1.TeamStatisticR\rteamStatistic\"\x8f\x01\n" +
	"\x05Goods\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\tR\agoodsId\x12%\n" +
	"\x0eoriginal_price\x18\x02 \x01(\x01R\roriginalPrice\x12'\n" +
	"\x0fdeduction_price\x18\x03 \x01(\x01R\x0edeductionPrice\x12\x1b\n" +
	"\tpay_price\x18\x04 \x01(\x01R\bpayPrice\"\xe6\x02\n" +
	"\x04Team\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\x03R\n" +
	"activityId\x12!\n" +
	"\ftarget_count\x18\x04 \x01(\x05R\vtargetCount\x12%\n" +
	"\x0ecomplete_count\x18\x05 \x01(\x05R\rcompleteCount\x12\x1d\n" +
	"\n" +
	"lock_count\x18\x06 \x01(\x05R\tlockCount\x12(\n" +
	"\x10valid_start_time\x18\a \x01(\x03R\x0evalidStartTime\x12$\n" +
	"\x0evalid_end_time\x18\b \x01(\x03R\fvalidEndTime\x120\n" +
	"\x14valid_time_countdown\x18\t \x01(\tR\x12validTimeCountdown\x12 \n" +
	"\fout_trade_no\x18\n" +
	" \x01(\tR\n" +
	"outTradeNo\"\x9b\x01\n" +
	"\rTeamStatistic\x12$\n" +
	"\x0eall_team_count\x18\x01 \x01(\x05R\fallTeamCount\x125\n" +
	"\x17all_team_complete_count\x18\x02 \x01(\x05R\x14allTeamCompleteCount\x12-\n" +
	"\x13all_team_user_count\x18\x03 \x01(\x05R\x10allTeamUserCount2\xa8\x01\n" +
	"\tIndexHTTP\x12\x9a\x01\n" +
	"\x19QueryGroupBuyMarketConfig\x12(.api.v1.QueryGroupBuyMarketConfigRequest\x1a&.api.v1.QueryGroupBuyMarketConfigReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /index/queryGroupBuyMarketConfigB\x1fZ\x1dgroup-buy-market-go/api/v1;v1b\x06proto3"

var (
	file_api_v1_index_proto_rawDescOnce sync.Once
	file_api_v1_index_proto_rawDescData []byte
)

func file_api_v1_index_proto_rawDescGZIP() []byte {
	file_api_v1_index_proto_rawDescOnce.Do(func() {
		file_api_v1_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_index_proto_rawDesc), len(file_api_v1_index_proto_rawDesc)))
	})
	return file_api_v1_index_proto_rawDescData
}

var file_api_v1_index_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_index_proto_goTypes = []any{
	(*QueryGroupBuyMarketConfigRequest)(nil), // 0: api.v1.QueryGroupBuyMarketConfigRequest
	(*QueryGroupBuyMarketConfigReply)(nil),   // 1: api.v1.QueryGroupBuyMarketConfigReply
	(*Goods)(nil),                            // 2: api.v1.Goods
	(*Team)(nil),                             // 3: api.v1.Team
	(*TeamStatistic)(nil),                    // 4: api.v1.TeamStatistic
}
var file_api_v1_index_proto_depIdxs = []int32{
	2, // 0: api.v1.QueryGroupBuyMarketConfigReply.goods:type_name -> api.v1.Goods
	3, // 1: api.v1.QueryGroupBuyMarketConfigReply.team_list:type_name -> api.v1.Team
	4, // 2: api.v1.QueryGroupBuyMarketConfigReply.team_statistic:type_name -> api.v1.TeamStatistic
	0, // 3: api.v1.IndexHTTP.QueryGroupBuyMarketConfig:input_type -> api.v1.QueryGroupBuyMarketConfigRequest
	1, // 4: api.v1.IndexHTTP.QueryGroupBuyMarketConfig:output_type -> api.v1.QueryGroupBuyMarketConfigReply
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_index_proto_init() }
func file_api_v1_index_proto_init() {
	if File_api_v1_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_index_proto_rawDesc), len(file_api_v1_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_index_proto_goTypes,
		DependencyIndexes: file_api_v1_index_proto_depIdxs,
		MessageInfos:      file_api_v1_index_proto_msgTypes,
	}.Build()
	File_api_v1_index_proto = out.File
	file_api_v1_index_proto_goTypes = nil
	file_api_v1_index_proto_depIdxs = nil
}
