// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: api/v1/tag.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecTagBatchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         string                 `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	BatchId       string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecTagBatchJobRequest) Reset() {
	*x = ExecTagBatchJobRequest{}
	mi := &file_api_v1_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecTagBatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecTagBatchJobRequest) ProtoMessage() {}

func (x *ExecTagBatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecTagBatchJobRequest.ProtoReflect.Descriptor instead.
func (*ExecTagBatchJobRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_proto_rawDescGZIP(), []int{0}
}

func (x *ExecTagBatchJobRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *ExecTagBatchJobRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type ExecTagBatchJobReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecTagBatchJobReply) Reset() {
	*x = ExecTagBatchJobReply{}
	mi := &file_api_v1_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecTagBatchJobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecTagBatchJobReply) ProtoMessage() {}

func (x *ExecTagBatchJobReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecTagBatchJobReply.ProtoReflect.Descriptor instead.
func (*ExecTagBatchJobReply) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_proto_rawDescGZIP(), []int{1}
}

func (x *ExecTagBatchJobReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_v1_tag_proto protoreflect.FileDescriptor

const file_api_v1_tag_proto_rawDesc = "" +
	"\n" +
	"\x10api/v1/tag.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\"J\n" +
	"\x16ExecTagBatchJobRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\tR\x05tagId\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\"0\n" +
	"\x14ExecTagBatchJobReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2{\n" +
	"\aTagHTTP\x12p\n" +
	"\x0fExecTagBatchJob\x12\x1e.api.v1.ExecTagBatchJobRequest\x1a\x1c.api.v1.ExecTagBatchJobReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/tag/execTagBatchJobB\x1fZ\x1dgroup-buy-market-go/api/v1;v1b\x06proto3"

var (
	file_api_v1_tag_proto_rawDescOnce sync.Once
	file_api_v1_tag_proto_rawDescData []byte
)

func file_api_v1_tag_proto_rawDescGZIP() []byte {
	file_api_v1_tag_proto_rawDescOnce.Do(func() {
		file_api_v1_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_tag_proto_rawDesc), len(file_api_v1_tag_proto_rawDesc)))
	})
	return file_api_v1_tag_proto_rawDescData
}

var file_api_v1_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_tag_proto_goTypes = []any{
	(*ExecTagBatchJobRequest)(nil), // 0: api.v1.ExecTagBatchJobRequest
	(*ExecTagBatchJobReply)(nil),   // 1: api.v1.ExecTagBatchJobReply
}
var file_api_v1_tag_proto_depIdxs = []int32{
	0, // 0: api.v1.TagHTTP.ExecTagBatchJob:input_type -> api.v1.ExecTagBatchJobRequest
	1, // 1: api.v1.TagHTTP.ExecTagBatchJob:output_type -> api.v1.ExecTagBatchJobReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_tag_proto_init() }
func file_api_v1_tag_proto_init() {
	if File_api_v1_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_tag_proto_rawDesc), len(file_api_v1_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_tag_proto_goTypes,
		DependencyIndexes: file_api_v1_tag_proto_depIdxs,
		MessageInfos:      file_api_v1_tag_proto_msgTypes,
	}.Build()
	File_api_v1_tag_proto = out.File
	file_api_v1_tag_proto_goTypes = nil
	file_api_v1_tag_proto_depIdxs = nil
}
