// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.0
// source: api/v1/tag.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TagHTTP_ExecTagBatchJob_FullMethodName = "/api.v1.TagHTTP/ExecTagBatchJob"
)

// TagHTTPClient is the client API for TagHTTP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TagService HTTP API
type TagHTTPClient interface {
	// ExecTagBatchJob
	ExecTagBatchJob(ctx context.Context, in *ExecTagBatchJobRequest, opts ...grpc.CallOption) (*ExecTagBatchJobReply, error)
}

type tagHTTPClient struct {
	cc grpc.ClientConnInterface
}

func NewTagHTTPClient(cc grpc.ClientConnInterface) TagHTTPClient {
	return &tagHTTPClient{cc}
}

func (c *tagHTTPClient) ExecTagBatchJob(ctx context.Context, in *ExecTagBatchJobRequest, opts ...grpc.CallOption) (*ExecTagBatchJobReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecTagBatchJobReply)
	err := c.cc.Invoke(ctx, TagHTTP_ExecTagBatchJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagHTTPServer is the server API for TagHTTP service.
// All implementations must embed UnimplementedTagHTTPServer
// for forward compatibility.
//
// TagService HTTP API
type TagHTTPServer interface {
	// ExecTagBatchJob
	ExecTagBatchJob(context.Context, *ExecTagBatchJobRequest) (*ExecTagBatchJobReply, error)
	mustEmbedUnimplementedTagHTTPServer()
}

// UnimplementedTagHTTPServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTagHTTPServer struct{}

func (UnimplementedTagHTTPServer) ExecTagBatchJob(context.Context, *ExecTagBatchJobRequest) (*ExecTagBatchJobReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecTagBatchJob not implemented")
}
func (UnimplementedTagHTTPServer) mustEmbedUnimplementedTagHTTPServer() {}
func (UnimplementedTagHTTPServer) testEmbeddedByValue()                 {}

// UnsafeTagHTTPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TagHTTPServer will
// result in compilation errors.
type UnsafeTagHTTPServer interface {
	mustEmbedUnimplementedTagHTTPServer()
}

func RegisterTagHTTPServer(s grpc.ServiceRegistrar, srv TagHTTPServer) {
	// If the following call panics, it indicates UnimplementedTagHTTPServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TagHTTP_ServiceDesc, srv)
}

func _TagHTTP_ExecTagBatchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecTagBatchJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagHTTPServer).ExecTagBatchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagHTTP_ExecTagBatchJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagHTTPServer).ExecTagBatchJob(ctx, req.(*ExecTagBatchJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TagHTTP_ServiceDesc is the grpc.ServiceDesc for TagHTTP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TagHTTP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.TagHTTP",
	HandlerType: (*TagHTTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecTagBatchJob",
			Handler:    _TagHTTP_ExecTagBatchJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/tag.proto",
}
