// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.27.0
// source: api/v1/tag.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTagHTTPExecTagBatchJob = "/api.v1.TagHTTP/ExecTagBatchJob"

type TagHTTPHTTPServer interface {
	// ExecTagBatchJob MarketTrial handles market trial requests
	ExecTagBatchJob(context.Context, *ExecTagBatchJobRequest) (*ExecTagBatchJobReply, error)
}

func RegisterTagHTTPHTTPServer(s *http.Server, srv TagHTTPHTTPServer) {
	r := s.Route("/")
	r.POST("/tag/execTagBatchJob", _TagHTTP_ExecTagBatchJob0_HTTP_Handler(srv))
}

func _TagHTTP_ExecTagBatchJob0_HTTP_Handler(srv TagHTTPHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecTagBatchJobRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagHTTPExecTagBatchJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExecTagBatchJob(ctx, req.(*ExecTagBatchJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecTagBatchJobReply)
		return ctx.Result(200, reply)
	}
}

type TagHTTPHTTPClient interface {
	// ExecTagBatchJob MarketTrial handles market trial requests
	ExecTagBatchJob(ctx context.Context, req *ExecTagBatchJobRequest, opts ...http.CallOption) (rsp *ExecTagBatchJobReply, err error)
}

type TagHTTPHTTPClientImpl struct {
	cc *http.Client
}

func NewTagHTTPHTTPClient(client *http.Client) TagHTTPHTTPClient {
	return &TagHTTPHTTPClientImpl{client}
}

// ExecTagBatchJob MarketTrial handles market trial requests
func (c *TagHTTPHTTPClientImpl) ExecTagBatchJob(ctx context.Context, in *ExecTagBatchJobRequest, opts ...http.CallOption) (*ExecTagBatchJobReply, error) {
	var out ExecTagBatchJobReply
	pattern := "/tag/execTagBatchJob"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTagHTTPExecTagBatchJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
