// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.27.0
// source: api/v1/trade.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTradeHTTPLockMarketPayOrder = "/api.v1.TradeHTTP/LockMarketPayOrder"

type TradeHTTPHTTPServer interface {
	// LockMarketPayOrder QueryNoPayMarketPayOrderByOutTradeNo 查询未支付的营销订单
	LockMarketPayOrder(context.Context, *LockMarketPayOrderRequest) (*LockMarketPayOrderReply, error)
}

func RegisterTradeHTTPHTTPServer(s *http.Server, srv TradeHTTPHTTPServer) {
	r := s.Route("/")
	r.POST("/trade/lockMarketPayOrder", _TradeHTTP_LockMarketPayOrder0_HTTP_Handler(srv))
}

func _TradeHTTP_LockMarketPayOrder0_HTTP_Handler(srv TradeHTTPHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LockMarketPayOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTradeHTTPLockMarketPayOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LockMarketPayOrder(ctx, req.(*LockMarketPayOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LockMarketPayOrderReply)
		return ctx.Result(200, reply)
	}
}

type TradeHTTPHTTPClient interface {
	// LockMarketPayOrder QueryNoPayMarketPayOrderByOutTradeNo 查询未支付的营销订单
	LockMarketPayOrder(ctx context.Context, req *LockMarketPayOrderRequest, opts ...http.CallOption) (rsp *LockMarketPayOrderReply, err error)
}

type TradeHTTPHTTPClientImpl struct {
	cc *http.Client
}

func NewTradeHTTPHTTPClient(client *http.Client) TradeHTTPHTTPClient {
	return &TradeHTTPHTTPClientImpl{client}
}

// LockMarketPayOrder QueryNoPayMarketPayOrderByOutTradeNo 查询未支付的营销订单
func (c *TradeHTTPHTTPClientImpl) LockMarketPayOrder(ctx context.Context, in *LockMarketPayOrderRequest, opts ...http.CallOption) (*LockMarketPayOrderReply, error) {
	var out LockMarketPayOrderReply
	pattern := "/trade/lockMarketPayOrder"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTradeHTTPLockMarketPayOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
