// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.0
// source: api/v1/trade.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeHTTP_LockMarketPayOrder_FullMethodName = "/api.v1.TradeHTTP/LockMarketPayOrder"
)

// TradeHTTPClient is the client API for TradeHTTP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TradeService HTTP API
type TradeHTTPClient interface {
	// QueryNoPayMarketPayOrderByOutTradeNo 查询未支付的营销订单
	LockMarketPayOrder(ctx context.Context, in *LockMarketPayOrderRequest, opts ...grpc.CallOption) (*LockMarketPayOrderReply, error)
}

type tradeHTTPClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeHTTPClient(cc grpc.ClientConnInterface) TradeHTTPClient {
	return &tradeHTTPClient{cc}
}

func (c *tradeHTTPClient) LockMarketPayOrder(ctx context.Context, in *LockMarketPayOrderRequest, opts ...grpc.CallOption) (*LockMarketPayOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockMarketPayOrderReply)
	err := c.cc.Invoke(ctx, TradeHTTP_LockMarketPayOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeHTTPServer is the server API for TradeHTTP service.
// All implementations must embed UnimplementedTradeHTTPServer
// for forward compatibility.
//
// TradeService HTTP API
type TradeHTTPServer interface {
	// QueryNoPayMarketPayOrderByOutTradeNo 查询未支付的营销订单
	LockMarketPayOrder(context.Context, *LockMarketPayOrderRequest) (*LockMarketPayOrderReply, error)
	mustEmbedUnimplementedTradeHTTPServer()
}

// UnimplementedTradeHTTPServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeHTTPServer struct{}

func (UnimplementedTradeHTTPServer) LockMarketPayOrder(context.Context, *LockMarketPayOrderRequest) (*LockMarketPayOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LockMarketPayOrder not implemented")
}
func (UnimplementedTradeHTTPServer) mustEmbedUnimplementedTradeHTTPServer() {}
func (UnimplementedTradeHTTPServer) testEmbeddedByValue()                   {}

// UnsafeTradeHTTPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeHTTPServer will
// result in compilation errors.
type UnsafeTradeHTTPServer interface {
	mustEmbedUnimplementedTradeHTTPServer()
}

func RegisterTradeHTTPServer(s grpc.ServiceRegistrar, srv TradeHTTPServer) {
	// If the following call panics, it indicates UnimplementedTradeHTTPServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeHTTP_ServiceDesc, srv)
}

func _TradeHTTP_LockMarketPayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockMarketPayOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeHTTPServer).LockMarketPayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeHTTP_LockMarketPayOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeHTTPServer).LockMarketPayOrder(ctx, req.(*LockMarketPayOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeHTTP_ServiceDesc is the grpc.ServiceDesc for TradeHTTP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeHTTP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.TradeHTTP",
	HandlerType: (*TradeHTTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LockMarketPayOrder",
			Handler:    _TradeHTTP_LockMarketPayOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/trade.proto",
}
