// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: api/v1/trade.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockMarketPayOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	GoodsId       string                 `protobuf:"bytes,4,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Channel       string                 `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,7,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	OutTradeNo    string                 `protobuf:"bytes,8,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockMarketPayOrderRequest) Reset() {
	*x = LockMarketPayOrderRequest{}
	mi := &file_api_v1_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockMarketPayOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockMarketPayOrderRequest) ProtoMessage() {}

func (x *LockMarketPayOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockMarketPayOrderRequest.ProtoReflect.Descriptor instead.
func (*LockMarketPayOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_trade_proto_rawDescGZIP(), []int{0}
}

func (x *LockMarketPayOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LockMarketPayOrderRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *LockMarketPayOrderRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *LockMarketPayOrderRequest) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *LockMarketPayOrderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LockMarketPayOrderRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *LockMarketPayOrderRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *LockMarketPayOrderRequest) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

type LockMarketPayOrderReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DeductionPrice   float64                `protobuf:"fixed64,2,opt,name=deduction_price,json=deductionPrice,proto3" json:"deduction_price,omitempty"`
	TradeOrderStatus int32                  `protobuf:"varint,3,opt,name=trade_order_status,json=tradeOrderStatus,proto3" json:"trade_order_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LockMarketPayOrderReply) Reset() {
	*x = LockMarketPayOrderReply{}
	mi := &file_api_v1_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockMarketPayOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockMarketPayOrderReply) ProtoMessage() {}

func (x *LockMarketPayOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockMarketPayOrderReply.ProtoReflect.Descriptor instead.
func (*LockMarketPayOrderReply) Descriptor() ([]byte, []int) {
	return file_api_v1_trade_proto_rawDescGZIP(), []int{1}
}

func (x *LockMarketPayOrderReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *LockMarketPayOrderReply) GetDeductionPrice() float64 {
	if x != nil {
		return x.DeductionPrice
	}
	return 0
}

func (x *LockMarketPayOrderReply) GetTradeOrderStatus() int32 {
	if x != nil {
		return x.TradeOrderStatus
	}
	return 0
}

var File_api_v1_trade_proto protoreflect.FileDescriptor

const file_api_v1_trade_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/trade.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\"\xfc\x01\n" +
	"\x19LockMarketPayOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\x03R\n" +
	"activityId\x12\x19\n" +
	"\bgoods_id\x18\x04 \x01(\tR\agoodsId\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x18\n" +
	"\achannel\x18\x06 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"notify_url\x18\a \x01(\tR\tnotifyUrl\x12 \n" +
	"\fout_trade_no\x18\b \x01(\tR\n" +
	"outTradeNo\"\x8b\x01\n" +
	"\x17LockMarketPayOrderReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12'\n" +
	"\x0fdeduction_price\x18\x02 \x01(\x01R\x0edeductionPrice\x12,\n" +
	"\x12trade_order_status\x18\x03 \x01(\x05R\x10tradeOrderStatus2\x8b\x01\n" +
	"\tTradeHTTP\x12~\n" +
	"\x12LockMarketPayOrder\x12!.api.v1.LockMarketPayOrderRequest\x1a\x1f.api.v1.LockMarketPayOrderReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/trade/lockMarketPayOrderB\x1fZ\x1dgroup-buy-market-go/api/v1;v1b\x06proto3"

var (
	file_api_v1_trade_proto_rawDescOnce sync.Once
	file_api_v1_trade_proto_rawDescData []byte
)

func file_api_v1_trade_proto_rawDescGZIP() []byte {
	file_api_v1_trade_proto_rawDescOnce.Do(func() {
		file_api_v1_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_trade_proto_rawDesc), len(file_api_v1_trade_proto_rawDesc)))
	})
	return file_api_v1_trade_proto_rawDescData
}

var file_api_v1_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_trade_proto_goTypes = []any{
	(*LockMarketPayOrderRequest)(nil), // 0: api.v1.LockMarketPayOrderRequest
	(*LockMarketPayOrderReply)(nil),   // 1: api.v1.LockMarketPayOrderReply
}
var file_api_v1_trade_proto_depIdxs = []int32{
	0, // 0: api.v1.TradeHTTP.LockMarketPayOrder:input_type -> api.v1.LockMarketPayOrderRequest
	1, // 1: api.v1.TradeHTTP.LockMarketPayOrder:output_type -> api.v1.LockMarketPayOrderReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_trade_proto_init() }
func file_api_v1_trade_proto_init() {
	if File_api_v1_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_trade_proto_rawDesc), len(file_api_v1_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_trade_proto_goTypes,
		DependencyIndexes: file_api_v1_trade_proto_depIdxs,
		MessageInfos:      file_api_v1_trade_proto_msgTypes,
	}.Build()
	File_api_v1_trade_proto = out.File
	file_api_v1_trade_proto_goTypes = nil
	file_api_v1_trade_proto_depIdxs = nil
}
