// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: api/http/groupbuy.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActivitiesRequest) Reset() {
	*x = GetAllActivitiesRequest{}
	mi := &file_api_http_groupbuy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActivitiesRequest) ProtoMessage() {}

func (x *GetAllActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActivitiesRequest.ProtoReflect.Descriptor instead.
func (*GetAllActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{0}
}

type GetAllActivitiesReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Activities    []*GroupBuyActivityInfo `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActivitiesReply) Reset() {
	*x = GetAllActivitiesReply{}
	mi := &file_api_http_groupbuy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActivitiesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActivitiesReply) ProtoMessage() {}

func (x *GetAllActivitiesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActivitiesReply.ProtoReflect.Descriptor instead.
func (*GetAllActivitiesReply) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllActivitiesReply) GetActivities() []*GroupBuyActivityInfo {
	if x != nil {
		return x.Activities
	}
	return nil
}

type GetAllDiscountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDiscountsRequest) Reset() {
	*x = GetAllDiscountsRequest{}
	mi := &file_api_http_groupbuy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDiscountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDiscountsRequest) ProtoMessage() {}

func (x *GetAllDiscountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDiscountsRequest.ProtoReflect.Descriptor instead.
func (*GetAllDiscountsRequest) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{2}
}

type GetAllDiscountsReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Discounts     []*GroupBuyDiscountInfo `protobuf:"bytes,1,rep,name=discounts,proto3" json:"discounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDiscountsReply) Reset() {
	*x = GetAllDiscountsReply{}
	mi := &file_api_http_groupbuy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDiscountsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDiscountsReply) ProtoMessage() {}

func (x *GetAllDiscountsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDiscountsReply.ProtoReflect.Descriptor instead.
func (*GetAllDiscountsReply) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllDiscountsReply) GetDiscounts() []*GroupBuyDiscountInfo {
	if x != nil {
		return x.Discounts
	}
	return nil
}

type GetDiscountByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountByIDRequest) Reset() {
	*x = GetDiscountByIDRequest{}
	mi := &file_api_http_groupbuy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountByIDRequest) ProtoMessage() {}

func (x *GetDiscountByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDiscountByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{4}
}

func (x *GetDiscountByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDiscountByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Discount      *GroupBuyDiscountInfo  `protobuf:"bytes,1,opt,name=discount,proto3" json:"discount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountByIDReply) Reset() {
	*x = GetDiscountByIDReply{}
	mi := &file_api_http_groupbuy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountByIDReply) ProtoMessage() {}

func (x *GetDiscountByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountByIDReply.ProtoReflect.Descriptor instead.
func (*GetDiscountByIDReply) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{5}
}

func (x *GetDiscountByIDReply) GetDiscount() *GroupBuyDiscountInfo {
	if x != nil {
		return x.Discount
	}
	return nil
}

type MarketTrialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GoodsId       string                 `protobuf:"bytes,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketTrialRequest) Reset() {
	*x = MarketTrialRequest{}
	mi := &file_api_http_groupbuy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketTrialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketTrialRequest) ProtoMessage() {}

func (x *MarketTrialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketTrialRequest.ProtoReflect.Descriptor instead.
func (*MarketTrialRequest) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{6}
}

func (x *MarketTrialRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarketTrialRequest) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *MarketTrialRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MarketTrialRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type MarketTrialReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrialResult   *TrialBalanceInfo      `protobuf:"bytes,1,opt,name=trial_result,json=trialResult,proto3" json:"trial_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketTrialReply) Reset() {
	*x = MarketTrialReply{}
	mi := &file_api_http_groupbuy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketTrialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketTrialReply) ProtoMessage() {}

func (x *MarketTrialReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketTrialReply.ProtoReflect.Descriptor instead.
func (*MarketTrialReply) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{7}
}

func (x *MarketTrialReply) GetTrialResult() *TrialBalanceInfo {
	if x != nil {
		return x.TrialResult
	}
	return nil
}

type GroupBuyActivityInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActivityId       int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityName     string                 `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	Source           string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Channel          string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	GoodsId          string                 `protobuf:"bytes,5,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GroupBuyDiscount *GroupBuyDiscountInfo  `protobuf:"bytes,6,opt,name=group_buy_discount,json=groupBuyDiscount,proto3" json:"group_buy_discount,omitempty"`
	GroupType        int32                  `protobuf:"varint,7,opt,name=group_type,json=groupType,proto3" json:"group_type,omitempty"`
	TakeLimitCount   int32                  `protobuf:"varint,8,opt,name=take_limit_count,json=takeLimitCount,proto3" json:"take_limit_count,omitempty"`
	Target           int32                  `protobuf:"varint,9,opt,name=target,proto3" json:"target,omitempty"`
	ValidTime        int32                  `protobuf:"varint,10,opt,name=valid_time,json=validTime,proto3" json:"valid_time,omitempty"`
	Status           int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	StartTime        int64                  `protobuf:"varint,12,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime          int64                  `protobuf:"varint,13,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TagId            string                 `protobuf:"bytes,14,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	TagScope         string                 `protobuf:"bytes,15,opt,name=tag_scope,json=tagScope,proto3" json:"tag_scope,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupBuyActivityInfo) Reset() {
	*x = GroupBuyActivityInfo{}
	mi := &file_api_http_groupbuy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupBuyActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupBuyActivityInfo) ProtoMessage() {}

func (x *GroupBuyActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupBuyActivityInfo.ProtoReflect.Descriptor instead.
func (*GroupBuyActivityInfo) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{8}
}

func (x *GroupBuyActivityInfo) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GroupBuyActivityInfo) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *GroupBuyActivityInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GroupBuyActivityInfo) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GroupBuyActivityInfo) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *GroupBuyActivityInfo) GetGroupBuyDiscount() *GroupBuyDiscountInfo {
	if x != nil {
		return x.GroupBuyDiscount
	}
	return nil
}

func (x *GroupBuyActivityInfo) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *GroupBuyActivityInfo) GetTakeLimitCount() int32 {
	if x != nil {
		return x.TakeLimitCount
	}
	return 0
}

func (x *GroupBuyActivityInfo) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *GroupBuyActivityInfo) GetValidTime() int32 {
	if x != nil {
		return x.ValidTime
	}
	return 0
}

func (x *GroupBuyActivityInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupBuyActivityInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GroupBuyActivityInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GroupBuyActivityInfo) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *GroupBuyActivityInfo) GetTagScope() string {
	if x != nil {
		return x.TagScope
	}
	return ""
}

type GroupBuyDiscountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DiscountId    int32                  `protobuf:"varint,2,opt,name=discount_id,json=discountId,proto3" json:"discount_id,omitempty"`
	DiscountName  string                 `protobuf:"bytes,3,opt,name=discount_name,json=discountName,proto3" json:"discount_name,omitempty"`
	DiscountDesc  string                 `protobuf:"bytes,4,opt,name=discount_desc,json=discountDesc,proto3" json:"discount_desc,omitempty"`
	DiscountType  int32                  `protobuf:"varint,5,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	MarketPlan    string                 `protobuf:"bytes,6,opt,name=market_plan,json=marketPlan,proto3" json:"market_plan,omitempty"`
	MarketExpr    string                 `protobuf:"bytes,7,opt,name=market_expr,json=marketExpr,proto3" json:"market_expr,omitempty"`
	TagId         string                 `protobuf:"bytes,8,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	CreateTime    int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupBuyDiscountInfo) Reset() {
	*x = GroupBuyDiscountInfo{}
	mi := &file_api_http_groupbuy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupBuyDiscountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupBuyDiscountInfo) ProtoMessage() {}

func (x *GroupBuyDiscountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupBuyDiscountInfo.ProtoReflect.Descriptor instead.
func (*GroupBuyDiscountInfo) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{9}
}

func (x *GroupBuyDiscountInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupBuyDiscountInfo) GetDiscountId() int32 {
	if x != nil {
		return x.DiscountId
	}
	return 0
}

func (x *GroupBuyDiscountInfo) GetDiscountName() string {
	if x != nil {
		return x.DiscountName
	}
	return ""
}

func (x *GroupBuyDiscountInfo) GetDiscountDesc() string {
	if x != nil {
		return x.DiscountDesc
	}
	return ""
}

func (x *GroupBuyDiscountInfo) GetDiscountType() int32 {
	if x != nil {
		return x.DiscountType
	}
	return 0
}

func (x *GroupBuyDiscountInfo) GetMarketPlan() string {
	if x != nil {
		return x.MarketPlan
	}
	return ""
}

func (x *GroupBuyDiscountInfo) GetMarketExpr() string {
	if x != nil {
		return x.MarketExpr
	}
	return ""
}

func (x *GroupBuyDiscountInfo) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *GroupBuyDiscountInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GroupBuyDiscountInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type TrialBalanceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GoodsId        string                 `protobuf:"bytes,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsName      string                 `protobuf:"bytes,2,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	OriginalPrice  float64                `protobuf:"fixed64,3,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	DeductionPrice float64                `protobuf:"fixed64,4,opt,name=deduction_price,json=deductionPrice,proto3" json:"deduction_price,omitempty"`
	TargetCount    int32                  `protobuf:"varint,5,opt,name=target_count,json=targetCount,proto3" json:"target_count,omitempty"`
	StartTime      int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsVisible      bool                   `protobuf:"varint,8,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	IsEnable       bool                   `protobuf:"varint,9,opt,name=is_enable,json=isEnable,proto3" json:"is_enable,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrialBalanceInfo) Reset() {
	*x = TrialBalanceInfo{}
	mi := &file_api_http_groupbuy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrialBalanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrialBalanceInfo) ProtoMessage() {}

func (x *TrialBalanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_groupbuy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrialBalanceInfo.ProtoReflect.Descriptor instead.
func (*TrialBalanceInfo) Descriptor() ([]byte, []int) {
	return file_api_http_groupbuy_proto_rawDescGZIP(), []int{10}
}

func (x *TrialBalanceInfo) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *TrialBalanceInfo) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *TrialBalanceInfo) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *TrialBalanceInfo) GetDeductionPrice() float64 {
	if x != nil {
		return x.DeductionPrice
	}
	return 0
}

func (x *TrialBalanceInfo) GetTargetCount() int32 {
	if x != nil {
		return x.TargetCount
	}
	return 0
}

func (x *TrialBalanceInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TrialBalanceInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TrialBalanceInfo) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *TrialBalanceInfo) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

var File_api_http_groupbuy_proto protoreflect.FileDescriptor

const file_api_http_groupbuy_proto_rawDesc = "" +
	"\n" +
	"\x17api/http/groupbuy.proto\x12\bapi.http\x1a\x1cgoogle/api/annotations.proto\"\x19\n" +
	"\x17GetAllActivitiesRequest\"W\n" +
	"\x15GetAllActivitiesReply\x12>\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x1e.api.http.GroupBuyActivityInfoR\n" +
	"activities\"\x18\n" +
	"\x16GetAllDiscountsRequest\"T\n" +
	"\x14GetAllDiscountsReply\x12<\n" +
	"\tdiscounts\x18\x01 \x03(\v2\x1e.api.http.GroupBuyDiscountInfoR\tdiscounts\"(\n" +
	"\x16GetDiscountByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"R\n" +
	"\x14GetDiscountByIDReply\x12:\n" +
	"\bdiscount\x18\x01 \x01(\v2\x1e.api.http.GroupBuyDiscountInfoR\bdiscount\"z\n" +
	"\x12MarketTrialRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgoods_id\x18\x02 \x01(\tR\agoodsId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\"Q\n" +
	"\x10MarketTrialReply\x12=\n" +
	"\ftrial_result\x18\x01 \x01(\v2\x1a.api.http.TrialBalanceInfoR\vtrialResult\"\xfd\x03\n" +
	"\x14GroupBuyActivityInfo\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x19\n" +
	"\bgoods_id\x18\x05 \x01(\tR\agoodsId\x12L\n" +
	"\x12group_buy_discount\x18\x06 \x01(\v2\x1e.api.http.GroupBuyDiscountInfoR\x10groupBuyDiscount\x12\x1d\n" +
	"\n" +
	"group_type\x18\a \x01(\x05R\tgroupType\x12(\n" +
	"\x10take_limit_count\x18\b \x01(\x05R\x0etakeLimitCount\x12\x16\n" +
	"\x06target\x18\t \x01(\x05R\x06target\x12\x1d\n" +
	"\n" +
	"valid_time\x18\n" +
	" \x01(\x05R\tvalidTime\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\f \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\r \x01(\x03R\aendTime\x12\x15\n" +
	"\x06tag_id\x18\x0e \x01(\tR\x05tagId\x12\x1b\n" +
	"\ttag_scope\x18\x0f \x01(\tR\btagScope\"\xd1\x02\n" +
	"\x14GroupBuyDiscountInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vdiscount_id\x18\x02 \x01(\x05R\n" +
	"discountId\x12#\n" +
	"\rdiscount_name\x18\x03 \x01(\tR\fdiscountName\x12#\n" +
	"\rdiscount_desc\x18\x04 \x01(\tR\fdiscountDesc\x12#\n" +
	"\rdiscount_type\x18\x05 \x01(\x05R\fdiscountType\x12\x1f\n" +
	"\vmarket_plan\x18\x06 \x01(\tR\n" +
	"marketPlan\x12\x1f\n" +
	"\vmarket_expr\x18\a \x01(\tR\n" +
	"marketExpr\x12\x15\n" +
	"\x06tag_id\x18\b \x01(\tR\x05tagId\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\n" +
	" \x01(\x03R\n" +
	"updateTime\"\xb5\x02\n" +
	"\x10TrialBalanceInfo\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\tR\agoodsId\x12\x1d\n" +
	"\n" +
	"goods_name\x18\x02 \x01(\tR\tgoodsName\x12%\n" +
	"\x0eoriginal_price\x18\x03 \x01(\x01R\roriginalPrice\x12'\n" +
	"\x0fdeduction_price\x18\x04 \x01(\x01R\x0edeductionPrice\x12!\n" +
	"\ftarget_count\x18\x05 \x01(\x05R\vtargetCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x1d\n" +
	"\n" +
	"is_visible\x18\b \x01(\bR\tisVisible\x12\x1b\n" +
	"\tis_enable\x18\t \x01(\bR\bisEnable2\xc7\x03\n" +
	"\fGroupBuyHTTP\x12t\n" +
	"\x10GetAllActivities\x12!.api.http.GetAllActivitiesRequest\x1a\x1f.api.http.GetAllActivitiesReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/groupbuy/activities\x12p\n" +
	"\x0fGetAllDiscounts\x12 .api.http.GetAllDiscountsRequest\x1a\x1e.api.http.GetAllDiscountsReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/groupbuy/discounts\x12o\n" +
	"\x0fGetDiscountByID\x12 .api.http.GetDiscountByIDRequest\x1a\x1e.api.http.GetDiscountByIDReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/groupbuy/discount\x12^\n" +
	"\vMarketTrial\x12\x1c.api.http.MarketTrialRequest\x1a\x1a.api.http.MarketTrialReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/market/trialB!Z\x1fgroup-buy-market-go/api/http;v1b\x06proto3"

var (
	file_api_http_groupbuy_proto_rawDescOnce sync.Once
	file_api_http_groupbuy_proto_rawDescData []byte
)

func file_api_http_groupbuy_proto_rawDescGZIP() []byte {
	file_api_http_groupbuy_proto_rawDescOnce.Do(func() {
		file_api_http_groupbuy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_http_groupbuy_proto_rawDesc), len(file_api_http_groupbuy_proto_rawDesc)))
	})
	return file_api_http_groupbuy_proto_rawDescData
}

var file_api_http_groupbuy_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_http_groupbuy_proto_goTypes = []any{
	(*GetAllActivitiesRequest)(nil), // 0: api.http.GetAllActivitiesRequest
	(*GetAllActivitiesReply)(nil),   // 1: api.http.GetAllActivitiesReply
	(*GetAllDiscountsRequest)(nil),  // 2: api.http.GetAllDiscountsRequest
	(*GetAllDiscountsReply)(nil),    // 3: api.http.GetAllDiscountsReply
	(*GetDiscountByIDRequest)(nil),  // 4: api.http.GetDiscountByIDRequest
	(*GetDiscountByIDReply)(nil),    // 5: api.http.GetDiscountByIDReply
	(*MarketTrialRequest)(nil),      // 6: api.http.MarketTrialRequest
	(*MarketTrialReply)(nil),        // 7: api.http.MarketTrialReply
	(*GroupBuyActivityInfo)(nil),    // 8: api.http.GroupBuyActivityInfo
	(*GroupBuyDiscountInfo)(nil),    // 9: api.http.GroupBuyDiscountInfo
	(*TrialBalanceInfo)(nil),        // 10: api.http.TrialBalanceInfo
}
var file_api_http_groupbuy_proto_depIdxs = []int32{
	8,  // 0: api.http.GetAllActivitiesReply.activities:type_name -> api.http.GroupBuyActivityInfo
	9,  // 1: api.http.GetAllDiscountsReply.discounts:type_name -> api.http.GroupBuyDiscountInfo
	9,  // 2: api.http.GetDiscountByIDReply.discount:type_name -> api.http.GroupBuyDiscountInfo
	10, // 3: api.http.MarketTrialReply.trial_result:type_name -> api.http.TrialBalanceInfo
	9,  // 4: api.http.GroupBuyActivityInfo.group_buy_discount:type_name -> api.http.GroupBuyDiscountInfo
	0,  // 5: api.http.GroupBuyHTTP.GetAllActivities:input_type -> api.http.GetAllActivitiesRequest
	2,  // 6: api.http.GroupBuyHTTP.GetAllDiscounts:input_type -> api.http.GetAllDiscountsRequest
	4,  // 7: api.http.GroupBuyHTTP.GetDiscountByID:input_type -> api.http.GetDiscountByIDRequest
	6,  // 8: api.http.GroupBuyHTTP.MarketTrial:input_type -> api.http.MarketTrialRequest
	1,  // 9: api.http.GroupBuyHTTP.GetAllActivities:output_type -> api.http.GetAllActivitiesReply
	3,  // 10: api.http.GroupBuyHTTP.GetAllDiscounts:output_type -> api.http.GetAllDiscountsReply
	5,  // 11: api.http.GroupBuyHTTP.GetDiscountByID:output_type -> api.http.GetDiscountByIDReply
	7,  // 12: api.http.GroupBuyHTTP.MarketTrial:output_type -> api.http.MarketTrialReply
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_http_groupbuy_proto_init() }
func file_api_http_groupbuy_proto_init() {
	if File_api_http_groupbuy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_http_groupbuy_proto_rawDesc), len(file_api_http_groupbuy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_http_groupbuy_proto_goTypes,
		DependencyIndexes: file_api_http_groupbuy_proto_depIdxs,
		MessageInfos:      file_api_http_groupbuy_proto_msgTypes,
	}.Build()
	File_api_http_groupbuy_proto = out.File
	file_api_http_groupbuy_proto_goTypes = nil
	file_api_http_groupbuy_proto_depIdxs = nil
}
