// Code generated by Wire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/google/wire"
	"gorm.io/gorm"

	"group-buy-market-go/internal/domain/activity/service"
	"group-buy-market-go/internal/domain/activity/service/discount"
	"group-buy-market-go/internal/domain/activity/service/trial/node"
	"group-buy-market-go/internal/infrastructure/adapter/repository"
	"group-buy-market-go/internal/infrastructure/dao"
	"group-buy-market-go/internal/server"
)

func initializeServer(db *gorm.DB, logger log.Logger) (*server.Server, error) {
	panic(wire.Build(
		wire.Bind(new(dao.GroupBuyActivityDAO), new(*dao.MySQLGroupBuyActivityDAO)),
		wire.Bind(new(dao.GroupBuyDiscountDAO), new(*dao.MySQLGroupBuyDiscountDAO)),
		wire.Bind(new(dao.SkuDAO), new(*dao.MySQLSkuDAO)),
		dao.NewMySQLGroupBuyActivityDAO,
		dao.NewMySQLGroupBuyDiscountDAO,
		dao.NewMySQLSkuDAO,
		repository.NewActivityRepository,
		discount.NewZJCalculateService,
		discount.NewZKCalculateService,
		discount.NewMJCalculateService,
		discount.NewNCalculateService,
		node.NewEndNode,
		node.NewMarketNode,
		node.NewSwitchNode,
		node.NewRootNode,
		service.NewIIndexGroupBuyMarketService,
		server.NewServer,
	))
}
