// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"gorm.io/gorm"
	"group-buy-market-go/internal/domain/activity/service"
	"group-buy-market-go/internal/domain/activity/service/discount"
	"group-buy-market-go/internal/domain/activity/service/trial/node"
	"group-buy-market-go/internal/infrastructure/adapter/repository"
	"group-buy-market-go/internal/infrastructure/dao"
	"group-buy-market-go/internal/server"
)

// Injectors from wire.go:

func initializeServer(db *gorm.DB, logger log.Logger) (*server.Server, error) {
	mySQLGroupBuyActivityDAO := dao.NewMySQLGroupBuyActivityDAO(db)
	endNode := node.NewEndNode(logger)
	mySQLGroupBuyDiscountDAO := dao.NewMySQLGroupBuyDiscountDAO(db)
	mySQLSkuDAO := dao.NewMySQLSkuDAO(db)
	activityRepository := repository.NewActivityRepository(mySQLGroupBuyActivityDAO, mySQLGroupBuyDiscountDAO, mySQLSkuDAO)
	zjCalculateService := discount.NewZJCalculateService(logger)
	zkCalculateService := discount.NewZKCalculateService(logger)
	mjCalculateService := discount.NewMJCalculateService(logger)
	nCalculateService := discount.NewNCalculateService(logger)
	marketNode := node.NewMarketNode(endNode, activityRepository, zjCalculateService, zkCalculateService, mjCalculateService, nCalculateService, logger)
	switchNode := node.NewSwitchNode(marketNode, logger)
	rootNode := node.NewRootNode(switchNode, logger)
	iIndexGroupBuyMarketService := service.NewIIndexGroupBuyMarketService(rootNode)
	serverServer := server.NewServer(mySQLGroupBuyActivityDAO, iIndexGroupBuyMarketService)
	return serverServer, nil
}
