// Code generated by Wire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package main

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"group-buy-market-go/internal/conf"
	"group-buy-market-go/internal/domain/activity/service"
	"group-buy-market-go/internal/domain/activity/service/discount"
	"group-buy-market-go/internal/domain/activity/service/trial/node"
	"group-buy-market-go/internal/infrastructure/adapter/repository"
	"group-buy-market-go/internal/infrastructure/dao"
	"group-buy-market-go/internal/server"
)

func initializeServer(db *gorm.DB) (*server.Server, error) {
	panic(wire.Build(
		dao.NewMySQLGroupBuyActivityDAO,
		dao.NewMySQLGroupBuyDiscountDAO,
		dao.NewMySQLSkuDAO,
		domain.NewGroupBuyService,
		repository.NewActivityRepository,
		discount.NewZJCalculateService,
		discount.NewZKCalculateService,
		discount.NewMJCalculateService,
		discount.NewNCalculateService,
		node.NewEndNode,
		node.NewMarketNode,
		node.NewSwitchNode,
		node.NewRootNode,
		service.NewIIndexGroupBuyMarketService,
		server.NewServer,
	))
}
