// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"group-buy-market-go/internal/domain"
	"group-buy-market-go/internal/infrastructure"
	"group-buy-market-go/internal/interfaces/http"
)

// Injectors from wire.go:

func initializeServer(db *sql.DB) (*http.Server, error) {
	mySQLGroupBuyActivityRepository := infrastructure.NewMySQLGroupBuyActivityRepository(db)
	groupBuyService := domain.NewGroupBuyService(mySQLGroupBuyActivityRepository)
	server := http.NewServer(mySQLGroupBuyActivityRepository, groupBuyService)
	return server, nil
}
